/**
 * Shared validation constants and helpers.
 *
 * Single source of truth for patterns reused across routes.js, socketHandler.js,
 * and sub-route files. Consolidates previously duplicated constants.
 */

/** Worker IDs are 8-char hex strings generated by crypto.randomBytes */
export const VALID_WORKER_ID = /^[a-zA-Z0-9-]{1,36}$/;

/** Simple identifiers (session names, folder IDs, etc.) */
export const VALID_SIMPLE_ID = /^[a-zA-Z0-9_-]+$/;

/** Control characters including DEL (\x7f). Use .test(str) to detect, .replace(re, '') to strip. */
export const CONTROL_CHAR_RE = /[\x00-\x1f\x7f]/;

/** Global variant for .replace() calls that need to strip all control chars */
export const CONTROL_CHAR_RE_G = /[\x00-\x1f\x7f]/g;

/** Max label length for workers, templates, etc. */
export const MAX_LABEL_LENGTH = 200;

/** Max task/prompt length sent to workers */
export const MAX_TASK_LENGTH = 10000;

/** Max input length for worker stdin (1MB) */
export const MAX_INPUT_LENGTH = 1024 * 1024;

/** Validate that a session ID is a positive integer */
export function isValidSessionId(value) {
  return Number.isFinite(value) && value > 0 && Number.isInteger(value);
}
