/**
 * Shared validation constants and helpers.
 *
 * Single source of truth for patterns reused across routes.js, socketHandler.js,
 * and sub-route files. Consolidates previously duplicated constants.
 */

/** Worker IDs are 8-char hex strings generated by crypto.randomBytes */
export const VALID_WORKER_ID = /^[a-zA-Z0-9-]{1,36}$/;

/** Simple identifiers (session names, folder IDs, etc.) */
export const VALID_SIMPLE_ID = /^[a-zA-Z0-9_-]+$/;

/** Control characters including DEL (\x7f). Use .test(str) to detect, .replace(re, '') to strip. */
export const CONTROL_CHAR_RE = /[\x00-\x1f\x7f]/;

/** Global variant for .replace() calls that need to strip all control chars */
export const CONTROL_CHAR_RE_G = /[\x00-\x1f\x7f]/g;

/** Max label length for workers, templates, etc. */
export const MAX_LABEL_LENGTH = 200;

/** Max task/prompt length sent to workers */
export const MAX_TASK_LENGTH = 10000;

/** Max prompt length for headless/batch/integration endpoints */
export const MAX_PROMPT_LENGTH = 50000;

/** Max system prompt length */
export const MAX_SYSTEM_PROMPT_LENGTH = 32768;

/** Max input length for worker stdin (1MB) */
export const MAX_INPUT_LENGTH = 1024 * 1024;

/** Timeout bounds for headless/batch operations (ms) */
export const MIN_TIMEOUT_MS = 1000;
export const MAX_TIMEOUT_MS = 600000;

/** SQLite max integer (used for session ID range) */
export const MAX_SESSION_ID = 2147483647;

/** Database pragma defaults — shared across all SQLite instances */
export const DB_JOURNAL_SIZE_LIMIT = 50000000; // 50MB WAL limit
export const DB_BUSY_TIMEOUT = 5000; // 5s wait for locks

/** Validate that a session ID is a positive integer within SQLite range */
export function isValidSessionId(value) {
  return Number.isFinite(value) && value > 0 && Number.isInteger(value) && value < MAX_SESSION_ID;
}
